import {HorizontalBox} from "std-widgets.slint";
import { ItemTile } from "item-tile.slint";
import { ListItem } from "list-item.slint";

export component AppWindow inherits Window {

    in property <[ListItem]> items;

    in property <string> window_title;

    window_title <=> self.title;

    HorizontalBox {
        property <color> border_color: black;
        property <length> border_width: 1px;
        property <length> border_radius: 4px;
        for item in items: ItemTile {
            item: item;
            border_color: border_color;
            border_width: border_width;
            border_radius: border_radius;
        }
    }
}
