import {HorizontalBox, VerticalBox} from "std-widgets.slint";

export struct ListItem {
    text: string,
}

export component AppWindow inherits Window {

    in property <[ListItem]> items;

    in property <string> window_title;

    window_title <=> self.title;

    HorizontalBox {
        for item in items : VerticalBox {
            Text {
                text: item.text;
            }
        }
    }
}