import {HorizontalBox, VerticalBox} from "std-widgets.slint";

export struct ListItem {
    text: string,
}

export component AppWindow inherits Window {

    in property <[ListItem]> items;

    in property <string> window_title;

    window_title <=> self.title;

    HorizontalBox {
        for item in items: VerticalBox {
            property <color> border_color: black;
            property <length> border_width: 1px;
            property <length> border_radius: 4px;
            Rectangle {
                border-width: border_width;
                border-radius: border_radius;
                border-color: border_color;
                Text {
                    text: item.text;
                }
            }
        }
    }
}
